name: twenty21design
favicon: null
layout_spectrum: 0.4134820762556046
typography_spectrum: 0.8226719330996275
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.7159875808283687
  lightness: 0.21771429968066514
  saturation: 0.5515962422359735
  rhythmicContrast: 0.22698322171345353
purpose: []
