name: twenty21design
favicon: null
layout_spectrum: 0.18734
typography_spectrum: 0.13782
title: Portfolio Design
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#373737'
    - '#757575'
    - '#fbfbfb'
    - '#cbcbcb'
  brandStrength: 0.5625
  lightness: 0
  saturation: 1
  rhythmicContrast: 0
purpose: []
