name: twenty21design
favicon: null
layout_spectrum: 0.50417
typography_spectrum: 0.80894
title: Portfolio Design
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#373737'
    - '#757575'
    - '#fbfbfb'
    - '#cbcbcb'
  brandStrength: 1
  lightness: 0.5
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
