name: twenty21design
favicon: null
layout_spectrum: 0.87632
typography_spectrum: 0.15287
title: Portfolio Design
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#9b1412'
    - '#840a06'
    - '#990000'
    - '#ff0000'
  brandStrength: 0.0625
  lightness: 0.1875
  saturation: 1
  rhythmicContrast: 0.75
purpose: []
