name: twenty21design
favicon: null
layout_spectrum: 0.17077
typography_spectrum: 0.15287
title: Portfolio Design
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#9b1512'
    - '#393939'
    - '#878787'
  brandStrength: 0.7159875808283687
  lightness: 0.1875
  saturation: 1
  rhythmicContrast: 0.25
purpose: []
